source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

workspace '../GSKStretchyHeaderView'
project 'Example.xcodeproj'
plugin 'slather'

target 'Example' do
  pod 'GSKStretchyHeaderView', :path => '../'
  pod 'Masonry'

  target 'Tests' do
    inherit! :search_paths

    pod 'Expecta'
    pod 'OCMock'
  end
end