source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

workspace '../GSKStretchyHeaderView'
xcodeproj 'Example.xcodeproj'


target 'Example', :exclusive => true do
  pod 'GSKStretchyHeaderView', :path => '../'
  pod 'Masonry'
end

target 'Tests', :exclusive => true do
  pod 'GSKStretchyHeaderView', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
