source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GSKStretchyHeaderView_Example', :exclusive => true do
  pod 'GSKStretchyHeaderView', :path => '../'
end

target 'GSKStretchyHeaderView_Tests', :exclusive => true do
  pod 'GSKStretchyHeaderView', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
